import { z } from "zod";
import type { ApiContract } from "@/lib/hacksync/types";
import { validateContractPayload, type ValidationResult } from "@/lib/validation/contract-validator";

export interface ParsedProperty {
  name: string;
  type: "string" | "number" | "boolean" | "object" | "array" | "unknown";
  required: boolean;
  description?: string;
}

export class ContractEngine {
  /**
   * Validate runtime request or response payload against contract schema string.
   */
  validate(schemaStr: string | null | undefined, payload: unknown): ValidationResult {
    return validateContractPayload(schemaStr, payload);
  }

  /**
   * Parse a contract schema string into a structured property list.
   */
  parseProperties(schemaStr: string | null | undefined): ParsedProperty[] {
    if (!schemaStr || schemaStr.trim() === "" || schemaStr === "null") return [];

    try {
      const parsed = JSON.parse(schemaStr);
      if (typeof parsed !== "object" || parsed === null) return [];

      // JSON Schema Format
      if (parsed.type === "object" && parsed.properties) {
        const requiredSet = new Set(Array.isArray(parsed.required) ? parsed.required : []);
        return Object.entries(parsed.properties).map(([name, def]: [string, any]) => ({
          name,
          type: (def?.type as any) ?? "unknown",
          required: requiredSet.has(name),
          description: def?.description,
        }));
      }

      // Simple Key-Type Mapping
      return Object.entries(parsed).map(([name, typeVal]) => ({
        name,
        type: typeof typeVal === "string" ? (typeVal.toLowerCase() as any) : "unknown",
        required: true,
      }));
    } catch {
      return [];
    }
  }

  /**
   * Generate TypeScript interface code from contract schema definition.
   */
  generateTypeDefinition(interfaceName: string, schemaStr: string | null | undefined): string {
    const props = this.parseProperties(schemaStr);
    if (props.length === 0) {
      return `export interface ${interfaceName} {\n  [key: string]: unknown;\n}`;
    }

    const lines = props.map((p) => {
      const opt = p.required ? "" : "?";
      return `  ${p.name}${opt}: ${p.type};`;
    });

    return `export interface ${interfaceName} {\n${lines.join("\n")}\n}`;
  }

  /**
   * Generate full OpenAPI 3.0 specification JSON from list of contracts.
   */
  generateOpenApiSpec(contracts: ApiContract[], title = "HackSync API", version = "1.0.0"): Record<string, unknown> {
    const paths: Record<string, any> = {};

    for (const contract of contracts) {
      const route = contract.route;
      const method = contract.method.toLowerCase();

      if (!paths[route]) {
        paths[route] = {};
      }

      paths[route][method] = {
        summary: contract.summary || `${contract.method} ${contract.route}`,
        operationId: `${contract.method.toLowerCase()}_${contract.route.replace(/[^a-zA-Z0-9]/g, "_")}`,
        security: contract.auth_required ? [{ BearerAuth: [] }] : [],
        responses: {
          "200": {
            description: "Successful response",
            content: {
              "application/json": {
                schema: contract.response_schema ? JSON.parse(contract.response_schema) : { type: "object" },
              },
            },
          },
        },
      };

      if (contract.request_schema && (method === "post" || method === "put" || method === "patch")) {
        paths[route][method].requestBody = {
          required: true,
          content: {
            "application/json": {
              schema: JSON.parse(contract.request_schema),
            },
          },
        };
      }
    }

    return {
      openapi: "3.0.0",
      info: {
        title,
        version,
        description: "Generated by HackSync Single Source of Truth Contract Engine",
      },
      paths,
      components: {
        securitySchemes: {
          BearerAuth: {
            type: "http",
            scheme: "bearer",
            bearerFormat: "JWT",
          },
        },
      },
    };
  }

  /**
   * Generate realistic synthetic JSON mock data based on a JSON Schema or raw sample definition.
   */
  generateMockData(schemaStr: string | null | undefined): unknown {
    if (!schemaStr || schemaStr.trim() === "" || schemaStr === "null") {
      return { status: "success", timestamp: new Date().toISOString() };
    }

    try {
      const parsed = typeof schemaStr === "string" ? JSON.parse(schemaStr) : schemaStr;
      if (typeof parsed !== "object" || parsed === null) {
        return parsed;
      }

      return this.synthesizeValue(parsed);
    } catch {
      return { status: "success", raw: schemaStr };
    }
  }

  private synthesizeValue(node: any, fieldName = ""): any {
    if (!node || typeof node !== "object") return node;

    // Standard JSON Schema with explicit type
    if (typeof node.type === "string") {
      switch (node.type.toLowerCase()) {
        case "array": {
          const itemSchema = node.items ?? { type: "string" };
          return [
            this.synthesizeValue(itemSchema, `${fieldName || "item"}_1`),
            this.synthesizeValue(itemSchema, `${fieldName || "item"}_2`),
          ];
        }
        case "object": {
          if (node.properties && typeof node.properties === "object") {
            const obj: Record<string, any> = {};
            for (const [key, propDef] of Object.entries(node.properties)) {
              obj[key] = this.synthesizeValue(propDef, key);
            }
            return obj;
          }
          return {};
        }
        case "string": {
          if (node.enum && Array.isArray(node.enum) && node.enum.length > 0) {
            return node.enum[0];
          }
          const lower = fieldName.toLowerCase();
          if (node.format === "date-time" || lower.includes("time") || lower.includes("date") || lower.includes("at")) {
            return "2026-08-27T12:00:00.000Z";
          }
          if (lower.includes("email")) return "alex@campusmesh.dev";
          if (lower.includes("url") || lower.includes("link")) return "https://github.com/hacksync/project";
          if (lower.includes("attendee") || lower.includes("user")) return "usr_8923a1";
          if (lower.includes("id")) return `${fieldName.slice(0, 3) || "evt"}_${Math.random().toString(36).substring(2, 6)}`;
          if (lower.includes("title") || lower.includes("name")) {
            if (lower.includes("event") || lower.includes("hack")) return "Hackathon Opening Keynote & Team Formation";
            return "Main Stage Workshop";
          }
          if (lower.includes("desc") || lower.includes("summary")) return "Hands-on engineering workshop with live API and database synchronization.";
          if (lower.includes("role")) return "lead";
          if (lower.includes("status")) return "active";
          return node.example ?? node.default ?? "sample_value";
        }
        case "number":
        case "integer": {
          const lower = fieldName.toLowerCase();
          if (lower.includes("count") || lower.includes("total") || lower.includes("attendees")) return 42;
          if (lower.includes("status") || lower.includes("code")) return 200;
          if (lower.includes("score") || lower.includes("grade")) return 98;
          return node.example ?? node.default ?? 100;
        }
        case "boolean": {
          return node.example ?? node.default ?? true;
        }
        default:
          return node.example ?? null;
      }
    }

    // If node is an object with nested property mappings (e.g. { id: "string", title: "string" })
    if (!node.type && !node.properties) {
      const obj: Record<string, any> = {};
      for (const [key, val] of Object.entries(node)) {
        if (typeof val === "string") {
          obj[key] = this.synthesizeValue({ type: val }, key);
        } else if (typeof val === "object" && val !== null) {
          obj[key] = this.synthesizeValue(val, key);
        } else {
          obj[key] = val;
        }
      }
      return obj;
    }

    return node;
  }
}

export const contractEngine = new ContractEngine();
