import { z } from "zod";
import type { ApiContract } from "@/lib/hacksync/types";
import { validateContractPayload, type ValidationResult } from "@/lib/validation/contract-validator";

export interface ParsedProperty {
  name: string;
  type: "string" | "number" | "boolean" | "object" | "array" | "unknown";
  required: boolean;
  description?: string;
}

export class ContractEngine {
  /**
   * Validate runtime request or response payload against contract schema string.
   */
  validate(schemaStr: string | null | undefined, payload: unknown): ValidationResult {
    return validateContractPayload(schemaStr, payload);
  }

  /**
   * Parse a contract schema string into a structured property list.
   */
  parseProperties(schemaStr: string | null | undefined): ParsedProperty[] {
    if (!schemaStr || schemaStr.trim() === "" || schemaStr === "null") return [];

    try {
      const parsed = JSON.parse(schemaStr);
      if (typeof parsed !== "object" || parsed === null) return [];

      // JSON Schema Format
      if (parsed.type === "object" && parsed.properties) {
        const requiredSet = new Set(Array.isArray(parsed.required) ? parsed.required : []);
        return Object.entries(parsed.properties).map(([name, def]: [string, any]) => ({
          name,
          type: (def?.type as any) ?? "unknown",
          required: requiredSet.has(name),
          description: def?.description,
        }));
      }

      // Simple Key-Type Mapping
      return Object.entries(parsed).map(([name, typeVal]) => ({
        name,
        type: typeof typeVal === "string" ? (typeVal.toLowerCase() as any) : "unknown",
        required: true,
      }));
    } catch {
      return [];
    }
  }

  /**
   * Generate TypeScript interface code from contract schema definition.
   */
  generateTypeDefinition(interfaceName: string, schemaStr: string | null | undefined): string {
    const props = this.parseProperties(schemaStr);
    if (props.length === 0) {
      return `export interface ${interfaceName} {\n  [key: string]: unknown;\n}`;
    }

    const lines = props.map((p) => {
      const opt = p.required ? "" : "?";
      return `  ${p.name}${opt}: ${p.type};`;
    });

    return `export interface ${interfaceName} {\n${lines.join("\n")}\n}`;
  }

  /**
   * Generate full OpenAPI 3.0 specification JSON from list of contracts.
   */
  generateOpenApiSpec(contracts: ApiContract[], title = "HackSync API", version = "1.0.0"): Record<string, unknown> {
    const paths: Record<string, any> = {};

    for (const contract of contracts) {
      const route = contract.route;
      const method = contract.method.toLowerCase();

      if (!paths[route]) {
        paths[route] = {};
      }

      paths[route][method] = {
        summary: contract.summary || `${contract.method} ${contract.route}`,
        operationId: `${contract.method.toLowerCase()}_${contract.route.replace(/[^a-zA-Z0-9]/g, "_")}`,
        security: contract.auth_required ? [{ BearerAuth: [] }] : [],
        responses: {
          "200": {
            description: "Successful response",
            content: {
              "application/json": {
                schema: contract.response_schema ? JSON.parse(contract.response_schema) : { type: "object" },
              },
            },
          },
        },
      };

      if (contract.request_schema && (method === "post" || method === "put" || method === "patch")) {
        paths[route][method].requestBody = {
          required: true,
          content: {
            "application/json": {
              schema: JSON.parse(contract.request_schema),
            },
          },
        };
      }
    }

    return {
      openapi: "3.0.0",
      info: {
        title,
        version,
        description: "Generated by HackSync Single Source of Truth Contract Engine",
      },
      paths,
      components: {
        securitySchemes: {
          BearerAuth: {
            type: "http",
            scheme: "bearer",
            bearerFormat: "JWT",
          },
        },
      },
    };
  }
}

export const contractEngine = new ContractEngine();
