import type { Workspace } from "./types";

export const DEMO_WORKSPACE: Workspace = {
  project: {
    id: "demo-sandbox-project",
    name: "CampusMesh (Demo Sandbox)",
    description: "Campus event mesh built during hackathon with React, Node/Express and PostgreSQL.",
    repo_url: "https://github.com/hacksync/campusmesh",
    default_branch: "main",
    schema_version: "2.1.0",
    invite_code: "DEMO99",
    is_open_demo: true,
    demo_mode: true,
    created_by: "u1",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  members: [
    {
      id: "m1",
      project_id: "demo-sandbox-project",
      user_id: "u1",
      display_name: "Arjun Patel",
      email: "arjun@campusmesh.dev",
      role: "lead",
      branch_name: "main",
      working_area: "src/routes/dashboard",
      online: true,
      last_seen_at: new Date().toISOString(),
    },
    {
      id: "m2",
      project_id: "demo-sandbox-project",
      user_id: "u2",
      display_name: "Priya Sharma",
      email: "priya@campusmesh.dev",
      role: "frontend",
      branch_name: "feat/frontend-ui",
      working_area: "src/components/Events.tsx",
      online: true,
      last_seen_at: new Date().toISOString(),
    },
    {
      id: "m3",
      project_id: "demo-sandbox-project",
      user_id: "u3",
      display_name: "Rahul Verma",
      email: "rahul@campusmesh.dev",
      role: "backend",
      branch_name: "feat/api-layer",
      working_area: "src/routes/events.ts",
      online: true,
      last_seen_at: new Date().toISOString(),
    },
    {
      id: "m4",
      project_id: "demo-sandbox-project",
      user_id: "u4",
      display_name: "Meera Nair",
      email: "meera@campusmesh.dev",
      role: "database",
      branch_name: "feat/schema-v2",
      working_area: "database/migrations",
      online: false,
      last_seen_at: new Date().toISOString(),
    },
  ],
  contracts: [
    {
      id: "c1",
      project_id: "demo-sandbox-project",
      method: "GET",
      route: "/api/events",
      summary: "List all upcoming campus events",
      request_schema: '{ "query": { "limit?": "number" } }',
      response_schema: '[{ "id": "uuid", "title": "string", "startsAt": "iso" }]',
      auth_required: false,
      status: "live",
      owner_role: "backend",
      version: "v1",
      test_status: "passing",
      locked: true,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: "c2",
      project_id: "demo-sandbox-project",
      method: "POST",
      route: "/api/events/:id/rsvp",
      summary: "RSVP to event",
      request_schema: '{ "body": { "note": "string" } }',
      response_schema: '{ "success": true, "rsvpId": "uuid" }',
      auth_required: true,
      status: "live",
      owner_role: "backend",
      version: "v1",
      test_status: "passing",
      locked: true,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
  ],
  tables: [
    {
      id: "t1",
      project_id: "demo-sandbox-project",
      name: "events",
      description: "Club organized events",
      owner_role: "database",
      schema_version: "v2.1.0",
      migration_status: "applied",
      sql_definition: "CREATE TABLE events (id uuid primary key, title text not null);",
    },
    {
      id: "t2",
      project_id: "demo-sandbox-project",
      name: "rsvps",
      description: "RSVP attendance records",
      owner_role: "database",
      schema_version: "v2.1.0",
      migration_status: "applied",
      sql_definition: "CREATE TABLE rsvps (id uuid primary key, event_id uuid, attendee_id uuid);",
    },
  ],
  columns: [
    {
      id: "col1",
      table_id: "t1",
      project_id: "demo-sandbox-project",
      name: "id",
      data_type: "uuid",
      is_nullable: false,
      is_primary: true,
      is_indexed: true,
      references_table: null,
      ordinal: 1,
    },
    {
      id: "col2",
      table_id: "t1",
      project_id: "demo-sandbox-project",
      name: "title",
      data_type: "text",
      is_nullable: false,
      is_primary: false,
      is_indexed: false,
      references_table: null,
      ordinal: 2,
    },
  ],
  codeNodes: [
    {
      id: "code-1",
      project_id: "demo-sandbox-project",
      path: "src/App.tsx",
      parent_path: "src",
      kind: "file",
      area: "frontend",
      owner_role: "frontend",
      status: "done",
      language: "typescript",
      content: `import React, { useEffect, useState } from "react";\n\nexport function App() {\n  const [events, setEvents] = useState([]);\n\n  useEffect(() => {\n    fetch("/api/events")\n      .then(res => res.json())\n      .then(data => setEvents(data));\n  }, []);\n\n  return (\n    <div className="p-8">\n      <h1 className="text-2xl font-bold">CampusMesh Events</h1>\n      <div className="grid gap-4 mt-4">\n        {events.map(ev => (\n          <div key={ev.id} className="p-4 border rounded">\n            <h3>{ev.title}</h3>\n          </div>\n        ))}\n      </div>\n    </div>\n  );\n}\n`,
      updated_at: new Date().toISOString(),
    },
    {
      id: "code-2",
      project_id: "demo-sandbox-project",
      path: "src/routes/events.ts",
      parent_path: "src/routes",
      kind: "file",
      area: "backend",
      owner_role: "backend",
      status: "done",
      language: "typescript",
      content: `import { Router } from "express";\n\nexport const eventsRouter = Router();\n\neventsRouter.get("/api/events", async (req, res) => {\n  // Contract locked: GET /api/events\n  res.json([\n    { id: "e1", title: "Hackathon Kickoff Keynote", startsAt: new Date().toISOString() },\n    { id: "e2", title: "AI Workshop & Pitch Session", startsAt: new Date().toISOString() },\n  ]);\n});\n`,
      updated_at: new Date().toISOString(),
    },
    {
      id: "code-3",
      project_id: "demo-sandbox-project",
      path: "src/db/schema.sql",
      parent_path: "src/db",
      kind: "file",
      area: "database",
      owner_role: "database",
      status: "done",
      language: "sql",
      content: `-- CampusMesh Database Schema\nCREATE TABLE events (\n  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),\n  title TEXT NOT NULL,\n  starts_at TIMESTAMPTZ NOT NULL DEFAULT now()\n);\n\nCREATE TABLE rsvps (\n  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),\n  event_id UUID REFERENCES events(id) ON DELETE CASCADE,\n  attendee_id UUID NOT NULL,\n  created_at TIMESTAMPTZ DEFAULT now()\n);\n`,
      updated_at: new Date().toISOString(),
    },
    {
      id: "code-4",
      project_id: "demo-sandbox-project",
      path: "README.md",
      parent_path: null,
      kind: "file",
      area: "shared",
      owner_role: "lead",
      status: "done",
      language: "markdown",
      content: `# CampusMesh (Demo Sandbox)\n\nCampus event mesh built during hackathon with React, Node/Express and PostgreSQL.\n\n## Technical Tracks\n- **Frontend**: React + Tailwind CSS\n- **Backend**: Express + OpenAPI Contracts\n- **Database**: PostgreSQL Schema\n`,
      updated_at: new Date().toISOString(),
    },
  ],
  links: [
    {
      id: "lnk1",
      project_id: "demo-sandbox-project",
      from_node_id: "code-1",
      to_node_id: "code-2",
      contract_id: "c1",
      kind: "calls_api",
    },
  ],
  branches: [
    {
      id: "b1",
      project_id: "demo-sandbox-project",
      name: "main",
      owner_role: "lead",
      owner_name: "Arjun Patel",
      ahead: 0,
      behind: 0,
      merge_status: "clean",
      last_commit_sha: "7d95a28f",
      last_commit_message: "feat: Add Local File Workspace, CodeSync Engine & GitHub Push Integration",
      integration_ready: true,
      last_pushed_at: new Date().toISOString(),
    },
    {
      id: "b2",
      project_id: "demo-sandbox-project",
      name: "feat/frontend-ui",
      owner_role: "frontend",
      owner_name: "Priya Sharma",
      ahead: 2,
      behind: 0,
      merge_status: "clean",
      last_commit_sha: "a3b8901",
      last_commit_message: "feat: Add Events list grid and responsive cards",
      integration_ready: true,
      last_pushed_at: new Date().toISOString(),
    },
    {
      id: "b3",
      project_id: "demo-sandbox-project",
      name: "feat/api-layer",
      owner_role: "backend",
      owner_name: "Rahul Verma",
      ahead: 1,
      behind: 0,
      merge_status: "clean",
      last_commit_sha: "f1039bc",
      last_commit_message: "feat: Lock GET /api/events response schema",
      integration_ready: true,
      last_pushed_at: new Date().toISOString(),
    },
    {
      id: "b4",
      project_id: "demo-sandbox-project",
      name: "feat/schema-v2",
      owner_role: "database",
      owner_name: "Meera Nair",
      ahead: 1,
      behind: 0,
      merge_status: "clean",
      last_commit_sha: "d9910ae",
      last_commit_message: "migration: Add rsvps cascade constraints",
      integration_ready: true,
      last_pushed_at: new Date().toISOString(),
    },
  ],
  envVars: [],
  checks: [],
  tasks: [
    {
      id: "tsk1",
      project_id: "demo-sandbox-project",
      title: "Lock events GET contract",
      area: "backend",
      priority: "high",
      status: "done",
      assignee_role: "backend",
      depends_on: null,
      blocker: null,
      updated_at: new Date().toISOString(),
    },
    {
      id: "tsk2",
      project_id: "demo-sandbox-project",
      title: "Connect Frontend EventList component",
      area: "frontend",
      priority: "high",
      status: "in_progress",
      assignee_role: "frontend",
      depends_on: "GET /api/events",
      blocker: null,
      updated_at: new Date().toISOString(),
    },
  ],
  activity: [
    {
      id: "act1",
      project_id: "demo-sandbox-project",
      kind: "code",
      actor: "Arjun Patel",
      actor_role: "lead",
      message: "Executed CodeSync: Synchronized 4 files into shared project codebase",
      created_at: new Date().toISOString(),
    },
  ],
  notes: [],
  handoffs: [],
  comments: [],
};
