import type { Workspace, Project, Member, Task, ApiContract, DbTable, DbColumn } from "./types";

export const DEMO_PROJECT_ID = "demo-sandbox-project";
const NOW = new Date().toISOString();
const HOUR_AGO = new Date(Date.now() - 3_600_000).toISOString();

export const DEMO_PROJECT: Project = {
  id: DEMO_PROJECT_ID,
  name: "HackSync Demo Platform",
  description: "Real-time integration and truth control center for distributed hackathon teams",
  repo_url: "https://github.com/shreybhuva123-cyber/hacksync",
  default_branch: "main",
  schema_version: "2.1.0",
  invite_code: "DEMO2026",
  is_open_demo: true,
  demo_mode: true,
  created_by: null,
  created_at: NOW,
  updated_at: NOW,
};

export const DEMO_MEMBERS: Member[] = [
  {
    id: "m1",
    project_id: DEMO_PROJECT_ID,
    user_id: "u1",
    display_name: "Arjun Patel",
    email: "arjun@hacksync.dev",
    role: "lead",
    branch_name: "main",
    working_area: "src/routes/dashboard",
    online: true,
    last_seen_at: NOW,
  },
  {
    id: "m2",
    project_id: DEMO_PROJECT_ID,
    user_id: "u2",
    display_name: "Priya Sharma",
    email: "priya@hacksync.dev",
    role: "frontend",
    branch_name: "feat/event-list",
    working_area: "src/components/Events.tsx",
    online: true,
    last_seen_at: NOW,
  },
  {
    id: "m3",
    project_id: DEMO_PROJECT_ID,
    user_id: "u3",
    display_name: "Rahul Verma",
    email: "rahul@hacksync.dev",
    role: "backend",
    branch_name: "feat/rsvp-api",
    working_area: "src/routes/events.ts",
    online: true,
    last_seen_at: NOW,
  },
  {
    id: "m4",
    project_id: DEMO_PROJECT_ID,
    user_id: "u4",
    display_name: "Meera Nair",
    email: "meera@hacksync.dev",
    role: "database",
    branch_name: "feat/rsvp-schema",
    working_area: "database/migrations",
    online: false,
    last_seen_at: HOUR_AGO,
  },
];

export const DEMO_CONTRACTS: ApiContract[] = [
  {
    id: "c1",
    project_id: DEMO_PROJECT_ID,
    route: "/api/events",
    method: "GET",
    version: "v1",
    summary: "List upcoming hackathon events",
    status: "live",
    locked: true,
    auth_required: false,
    owner_role: "backend",
    request_schema: null,
    response_schema: JSON.stringify({
      events: [
        { id: "e1", title: "Hackathon Kickoff Keynote", time: "10:00 AM", location: "Auditorium A" },
        { id: "e2", title: "API Workshop & Mentoring", time: "02:00 PM", location: "Lab 3" },
      ],
    }),
    test_status: "passing",
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: "c2",
    project_id: DEMO_PROJECT_ID,
    route: "/api/events/:id/rsvp",
    method: "POST",
    version: "v1",
    summary: "RSVP attendee for a specific event",
    status: "live",
    locked: true,
    auth_required: true,
    owner_role: "backend",
    request_schema: JSON.stringify({ userId: "string", dietaryNeeds: "string" }),
    response_schema: JSON.stringify({ success: true, rsvpId: "rsvp-123", status: "confirmed" }),
    test_status: "passing",
    created_at: NOW,
    updated_at: NOW,
  },
];

export const DEMO_TABLES: DbTable[] = [
  {
    id: "t1",
    project_id: DEMO_PROJECT_ID,
    name: "events",
    owner_role: "database",
    schema_version: "2.1.0",
    migration_status: "applied",
    description: "Scheduled hackathon events and room locations",
    sql_definition: null,
  },
  {
    id: "t2",
    project_id: DEMO_PROJECT_ID,
    name: "event_rsvps",
    owner_role: "database",
    schema_version: "2.1.0",
    migration_status: "applied",
    description: "Attendee RSVPs linked to events",
    sql_definition: null,
  },
];

export const DEMO_COLUMNS: DbColumn[] = [
  {
    id: "col1",
    table_id: "t1",
    project_id: DEMO_PROJECT_ID,
    name: "id",
    data_type: "uuid",
    is_nullable: false,
    is_primary: true,
    is_indexed: true,
    references_table: null,
    ordinal: 1,
  },
  {
    id: "col2",
    table_id: "t1",
    project_id: DEMO_PROJECT_ID,
    name: "title",
    data_type: "text",
    is_nullable: false,
    is_primary: false,
    is_indexed: false,
    references_table: null,
    ordinal: 2,
  },
  {
    id: "col3",
    table_id: "t2",
    project_id: DEMO_PROJECT_ID,
    name: "id",
    data_type: "uuid",
    is_nullable: false,
    is_primary: true,
    is_indexed: true,
    references_table: null,
    ordinal: 1,
  },
  {
    id: "col4",
    table_id: "t2",
    project_id: DEMO_PROJECT_ID,
    name: "event_id",
    data_type: "uuid",
    is_nullable: false,
    is_primary: false,
    is_indexed: true,
    references_table: "events",
    ordinal: 2,
  },
];

export const DEMO_TASKS: Task[] = [
  {
    id: "tsk1",
    project_id: DEMO_PROJECT_ID,
    title: "Lock events GET contract",
    area: "backend",
    priority: "high",
    status: "done",
    assignee_role: "backend",
    depends_on: null,
    blocker: null,
    updated_at: NOW,
  },
  {
    id: "tsk2",
    project_id: DEMO_PROJECT_ID,
    title: "Connect Frontend EventList component",
    area: "frontend",
    priority: "high",
    status: "in_progress",
    assignee_role: "frontend",
    depends_on: "GET /api/events",
    blocker: null,
    updated_at: NOW,
  },
];

export const DEMO_WORKSPACE: Workspace = {
  project: DEMO_PROJECT,
  members: DEMO_MEMBERS,
  contracts: DEMO_CONTRACTS,
  tables: DEMO_TABLES,
  columns: DEMO_COLUMNS,
  tasks: DEMO_TASKS,
  codeNodes: [],
  links: [],
  branches: [],
  envVars: [],
  checks: [],
  activity: [
    {
      id: "act1",
      project_id: DEMO_PROJECT_ID,
      kind: "contract",
      actor: "Arjun Patel",
      actor_role: "lead",
      message: "Locked contract GET /api/events v1",
      created_at: NOW,
    },
  ],
  notes: [],
  handoffs: [],
  comments: [],
};
