/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedActivityRouteImport } from './routes/_authenticated/activity'
import { Route as AuthenticatedApiRouteImport } from './routes/_authenticated/api'
import { Route as AuthenticatedArchitectureRouteImport } from './routes/_authenticated/architecture'
import { Route as AuthenticatedCodeRouteImport } from './routes/_authenticated/code'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedEnvRouteImport } from './routes/_authenticated/env'
import { Route as AuthenticatedGitRouteImport } from './routes/_authenticated/git'
import { Route as AuthenticatedHandoffsRouteImport } from './routes/_authenticated/handoffs'
import { Route as AuthenticatedHealthRouteImport } from './routes/_authenticated/health'
import { Route as AuthenticatedIntegrationsRouteImport } from './routes/_authenticated/integrations'
import { Route as AuthenticatedPitchRouteImport } from './routes/_authenticated/pitch'
import { Route as AuthenticatedPredemoRouteImport } from './routes/_authenticated/predemo'
import { Route as AuthenticatedProjectsRouteImport } from './routes/_authenticated/projects'
import { Route as AuthenticatedSchemaRouteImport } from './routes/_authenticated/schema'
import { Route as AuthenticatedSecurityRouteImport } from './routes/_authenticated/security'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedSetupRouteImport } from './routes/_authenticated/setup'
import { Route as AuthenticatedTasksRouteImport } from './routes/_authenticated/tasks'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedActivityRoute = AuthenticatedActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedApiRoute = AuthenticatedApiRouteImport.update({
  id: '/api',
  path: '/api',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedArchitectureRoute =
  AuthenticatedArchitectureRouteImport.update({
    id: '/architecture',
    path: '/architecture',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCodeRoute = AuthenticatedCodeRouteImport.update({
  id: '/code',
  path: '/code',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEnvRoute = AuthenticatedEnvRouteImport.update({
  id: '/env',
  path: '/env',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGitRoute = AuthenticatedGitRouteImport.update({
  id: '/git',
  path: '/git',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHandoffsRoute = AuthenticatedHandoffsRouteImport.update({
  id: '/handoffs',
  path: '/handoffs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHealthRoute = AuthenticatedHealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedIntegrationsRoute =
  AuthenticatedIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPitchRoute = AuthenticatedPitchRouteImport.update({
  id: '/pitch',
  path: '/pitch',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPredemoRoute = AuthenticatedPredemoRouteImport.update({
  id: '/predemo',
  path: '/predemo',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProjectsRoute = AuthenticatedProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSchemaRoute = AuthenticatedSchemaRouteImport.update({
  id: '/schema',
  path: '/schema',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSecurityRoute = AuthenticatedSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSetupRoute = AuthenticatedSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTasksRoute = AuthenticatedTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/activity': typeof AuthenticatedActivityRoute
  '/api': typeof AuthenticatedApiRoute
  '/architecture': typeof AuthenticatedArchitectureRoute
  '/code': typeof AuthenticatedCodeRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/env': typeof AuthenticatedEnvRoute
  '/git': typeof AuthenticatedGitRoute
  '/handoffs': typeof AuthenticatedHandoffsRoute
  '/health': typeof AuthenticatedHealthRoute
  '/integrations': typeof AuthenticatedIntegrationsRoute
  '/pitch': typeof AuthenticatedPitchRoute
  '/predemo': typeof AuthenticatedPredemoRoute
  '/projects': typeof AuthenticatedProjectsRoute
  '/schema': typeof AuthenticatedSchemaRoute
  '/security': typeof AuthenticatedSecurityRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/setup': typeof AuthenticatedSetupRoute
  '/tasks': typeof AuthenticatedTasksRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/activity': typeof AuthenticatedActivityRoute
  '/api': typeof AuthenticatedApiRoute
  '/architecture': typeof AuthenticatedArchitectureRoute
  '/code': typeof AuthenticatedCodeRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/env': typeof AuthenticatedEnvRoute
  '/git': typeof AuthenticatedGitRoute
  '/handoffs': typeof AuthenticatedHandoffsRoute
  '/health': typeof AuthenticatedHealthRoute
  '/integrations': typeof AuthenticatedIntegrationsRoute
  '/pitch': typeof AuthenticatedPitchRoute
  '/predemo': typeof AuthenticatedPredemoRoute
  '/projects': typeof AuthenticatedProjectsRoute
  '/schema': typeof AuthenticatedSchemaRoute
  '/security': typeof AuthenticatedSecurityRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/setup': typeof AuthenticatedSetupRoute
  '/tasks': typeof AuthenticatedTasksRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/activity': typeof AuthenticatedActivityRoute
  '/_authenticated/api': typeof AuthenticatedApiRoute
  '/_authenticated/architecture': typeof AuthenticatedArchitectureRoute
  '/_authenticated/code': typeof AuthenticatedCodeRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/env': typeof AuthenticatedEnvRoute
  '/_authenticated/git': typeof AuthenticatedGitRoute
  '/_authenticated/handoffs': typeof AuthenticatedHandoffsRoute
  '/_authenticated/health': typeof AuthenticatedHealthRoute
  '/_authenticated/integrations': typeof AuthenticatedIntegrationsRoute
  '/_authenticated/pitch': typeof AuthenticatedPitchRoute
  '/_authenticated/predemo': typeof AuthenticatedPredemoRoute
  '/_authenticated/projects': typeof AuthenticatedProjectsRoute
  '/_authenticated/schema': typeof AuthenticatedSchemaRoute
  '/_authenticated/security': typeof AuthenticatedSecurityRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/setup': typeof AuthenticatedSetupRoute
  '/_authenticated/tasks': typeof AuthenticatedTasksRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/activity'
    | '/api'
    | '/architecture'
    | '/code'
    | '/dashboard'
    | '/env'
    | '/git'
    | '/handoffs'
    | '/health'
    | '/integrations'
    | '/pitch'
    | '/predemo'
    | '/projects'
    | '/schema'
    | '/security'
    | '/settings'
    | '/setup'
    | '/tasks'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/activity'
    | '/api'
    | '/architecture'
    | '/code'
    | '/dashboard'
    | '/env'
    | '/git'
    | '/handoffs'
    | '/health'
    | '/integrations'
    | '/pitch'
    | '/predemo'
    | '/projects'
    | '/schema'
    | '/security'
    | '/settings'
    | '/setup'
    | '/tasks'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/activity'
    | '/_authenticated/api'
    | '/_authenticated/architecture'
    | '/_authenticated/code'
    | '/_authenticated/dashboard'
    | '/_authenticated/env'
    | '/_authenticated/git'
    | '/_authenticated/handoffs'
    | '/_authenticated/health'
    | '/_authenticated/integrations'
    | '/_authenticated/pitch'
    | '/_authenticated/predemo'
    | '/_authenticated/projects'
    | '/_authenticated/schema'
    | '/_authenticated/security'
    | '/_authenticated/settings'
    | '/_authenticated/setup'
    | '/_authenticated/tasks'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/activity': {
      id: '/_authenticated/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof AuthenticatedActivityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/api': {
      id: '/_authenticated/api'
      path: '/api'
      fullPath: '/api'
      preLoaderRoute: typeof AuthenticatedApiRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/architecture': {
      id: '/_authenticated/architecture'
      path: '/architecture'
      fullPath: '/architecture'
      preLoaderRoute: typeof AuthenticatedArchitectureRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/code': {
      id: '/_authenticated/code'
      path: '/code'
      fullPath: '/code'
      preLoaderRoute: typeof AuthenticatedCodeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/env': {
      id: '/_authenticated/env'
      path: '/env'
      fullPath: '/env'
      preLoaderRoute: typeof AuthenticatedEnvRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/git': {
      id: '/_authenticated/git'
      path: '/git'
      fullPath: '/git'
      preLoaderRoute: typeof AuthenticatedGitRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/handoffs': {
      id: '/_authenticated/handoffs'
      path: '/handoffs'
      fullPath: '/handoffs'
      preLoaderRoute: typeof AuthenticatedHandoffsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/health': {
      id: '/_authenticated/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof AuthenticatedHealthRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/integrations': {
      id: '/_authenticated/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof AuthenticatedIntegrationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pitch': {
      id: '/_authenticated/pitch'
      path: '/pitch'
      fullPath: '/pitch'
      preLoaderRoute: typeof AuthenticatedPitchRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/predemo': {
      id: '/_authenticated/predemo'
      path: '/predemo'
      fullPath: '/predemo'
      preLoaderRoute: typeof AuthenticatedPredemoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects': {
      id: '/_authenticated/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AuthenticatedProjectsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/schema': {
      id: '/_authenticated/schema'
      path: '/schema'
      fullPath: '/schema'
      preLoaderRoute: typeof AuthenticatedSchemaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/security': {
      id: '/_authenticated/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof AuthenticatedSecurityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/setup': {
      id: '/_authenticated/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof AuthenticatedSetupRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tasks': {
      id: '/_authenticated/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthenticatedTasksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedActivityRoute: typeof AuthenticatedActivityRoute
  AuthenticatedApiRoute: typeof AuthenticatedApiRoute
  AuthenticatedArchitectureRoute: typeof AuthenticatedArchitectureRoute
  AuthenticatedCodeRoute: typeof AuthenticatedCodeRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEnvRoute: typeof AuthenticatedEnvRoute
  AuthenticatedGitRoute: typeof AuthenticatedGitRoute
  AuthenticatedHandoffsRoute: typeof AuthenticatedHandoffsRoute
  AuthenticatedHealthRoute: typeof AuthenticatedHealthRoute
  AuthenticatedIntegrationsRoute: typeof AuthenticatedIntegrationsRoute
  AuthenticatedPitchRoute: typeof AuthenticatedPitchRoute
  AuthenticatedPredemoRoute: typeof AuthenticatedPredemoRoute
  AuthenticatedProjectsRoute: typeof AuthenticatedProjectsRoute
  AuthenticatedSchemaRoute: typeof AuthenticatedSchemaRoute
  AuthenticatedSecurityRoute: typeof AuthenticatedSecurityRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSetupRoute: typeof AuthenticatedSetupRoute
  AuthenticatedTasksRoute: typeof AuthenticatedTasksRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedActivityRoute: AuthenticatedActivityRoute,
  AuthenticatedApiRoute: AuthenticatedApiRoute,
  AuthenticatedArchitectureRoute: AuthenticatedArchitectureRoute,
  AuthenticatedCodeRoute: AuthenticatedCodeRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEnvRoute: AuthenticatedEnvRoute,
  AuthenticatedGitRoute: AuthenticatedGitRoute,
  AuthenticatedHandoffsRoute: AuthenticatedHandoffsRoute,
  AuthenticatedHealthRoute: AuthenticatedHealthRoute,
  AuthenticatedIntegrationsRoute: AuthenticatedIntegrationsRoute,
  AuthenticatedPitchRoute: AuthenticatedPitchRoute,
  AuthenticatedPredemoRoute: AuthenticatedPredemoRoute,
  AuthenticatedProjectsRoute: AuthenticatedProjectsRoute,
  AuthenticatedSchemaRoute: AuthenticatedSchemaRoute,
  AuthenticatedSecurityRoute: AuthenticatedSecurityRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSetupRoute: AuthenticatedSetupRoute,
  AuthenticatedTasksRoute: AuthenticatedTasksRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
